# optional since v1.27.0 - 
# removed version to include condition in depends_on
# version: '3.9'
services:
    api:
        build: .
        platform: linux/amd64
        container_name: spring-boot
        ports:
            - "8080:8080"
        labels:
            - "api.version=0.1"    
        restart: always
        networks:
            - api-network
            - db-network
        depends_on:
            database:
                condition: service_healthy
    database:
        image: mongo:4.4.15
        container_name: mongodb
        volumes:
            - ./db:/data/db
        environment:
            - MONGO_INITDB_DATABASE=employee
        networks:
            - db-network
        restart: always
        # inject the environment variables defined in the file "mongo.env"
        env_file:
            - mongo.env
        healthcheck:
            test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 20s

# by default, networks are named as <compose-dir>-<network name>
networks:
    api-network:
        name: apis
        driver: bridge
    db-network:
        name: db
        driver: bridge